# Generated by Django 4.2.1 on 2023-05-21 10:20

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Biens",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Code_region", models.CharField(max_length=100)),
                ("Date_mutation", models.CharField(max_length=100)),
                ("Code_departement", models.CharField(max_length=100)),
                ("Valeur_fonciere", models.CharField(max_length=100)),
                ("Surface_terrain", models.CharField(max_length=100)),
                ("m2", models.CharField(max_length=100)),
            ],
        ),
    ]
